<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error Class</title>
</head>
<body>
    <script>
        
        class ValidationError extends Error {
            constructor(message, field) {
                super(message)
                this.field = field
            }
        }

        class MathUtil {

            static sum(...numbers) {
                
                if (numbers.length === 0) {
                    throw new ValidationError("Total parameter must more than 0", "numbers")
                } 
                let total = 0
                for (const number of numbers) {
                    total += number
                }
                return total
            }
        }

        try{
            console.info(MathUtil.sum())
            console.info("Shaufi")
        } catch(error) {
            if (error instanceof ValidationError) {
                console.info(`an error occurred in field: ${error.field} with error ${error.message} `)
            } else {
                console.info(`an error occurred: ${error.message}`)
            }
        } finally {
            console.info("Program is complete")
        }

        console.info("Imanulhaq")

    </script>
</body>
</html>